### ISSUE TITLE
Does 'hu.bme.mit.ocl2iq.mapping' can used in VIATRA3？

### ISSUE THREAD

**Issue by nicholaskong** [viatra/EMF-IncQuery-Addons#3]
Now, I want to transfer the OCL to VQL, I find this plugin can do this operation.
But I see this project have more than 3 years not change, and maybe it is not support VIATRA3?
Does any one know how I change it to support VIATRA3?

**Comment by bergmanngabor** [comment]
Since the VIATRA Query `.vql` syntax is very similar to the earlier syntax of `.eiq`, queries generated with OCL2IQ should work just fine in modern builds as well. If you find that this is not true for your case, please tell us :)

**Comment by nicholaskong** [comment]
Thanks for you replay Bergmann. I have read your paper about OCL to Graph Patterns.

As you said that 'currently only a subset of transformation is actually implemented', and 'Due to the expressive power of OCL constructs, the Rete-based approach used in EMF-IncQuery is not applicable for
all queries formulated as OCL expressions.'

All of these conclusion are a few years ago. Now, do you have made any progress on OCL to Graph Patterns (VQL)? I am very interest in this part.

Thanks a lot.

**Comment by bergmanngabor** [comment]
> Now, do you have made any progress on OCL to Graph Patterns (VQL)? 

No, I did not. I was waiting for interested users to show up :)
Does the current version of the transformation cover your use cases, or would you like some specific improvements?

> 'Due to the expressive power of OCL constructs, the Rete-based approach used in EMF-IncQuery is not applicable for all queries formulated as OCL expressions.'

Viatra Query now supports more aggregators (sum, min, etc.) that have not yet been added to the transformation. However, the fundamental truth has not changed: the expressive power of OCL is beyond that of graph queries (even with the extensions we provide).

**Comment by nicholaskong** [comment]
No, I did not. I was waiting for interested users to show up :)
Does the current version of the transformation cover your use cases, or would you like some specific improvements?

-- I want find a way/tool which can transfer the OCL to graph queries. I am not sure whether it can cover our use case. I think maybe we need to further research this area.  If I have any problem, I hope maybe I can ask for your some help.
Thank you very much. ( ;
